spring:
  application:
    name: auth2
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8100/realms/sushi-restaurant-dev/protocol/openid-connect/certs"




